development:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['DATABASE_NAME']%>
  pool: 2
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['HOST_NAME'] %>

production:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['DATABASE_NAME']%>
  pool: 2
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['HOST_NAME'] %>
